work day part:
    cargo watch -w {{day}} -x "check -p {{day}}" -s "just test {{day}} {{part}}" -s "just lint {{day}}"
answer day part:
    cargo run --release -p {{day}} --bin {{part}}
lint day:
    cargo clippy -p {{day}}
test day part:
    cargo nextest run -p {{day}} {{part}}
bench-all:
    cargo bench -q > benchmarks.txt
bench day part:
    cargo bench --bench {{day}}-bench {{part}} >> {{day}}.bench.txt

create day:
    cargo generate --path ./daily-template --name {{day}}
    just get-input {{day}}

get-input day:
  ./get-input.ts {{day}} > {{day}}/input.txt

